Added truecrypt, but it does not compile yet since it's dependency wxWidgets fails to build ...
Maybe someone wants to take a look at it.

--------------------
building wxbuild
Configuring wxWidgets library...
configure: WARNING: libSM not found; disabling session management detection
Building wxWidgets library...
building .pch/wxprec_baselib/wx/wxprec.h.gch
/nix/store/b2gmgy8y6nidjj7n34jx4sanrjdaxrw3-glibc-2.7/lib/crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: ld returned 1 exit status
make[1]: *** [.pch/wxprec_baselib/wx/wxprec.h.gch] Error 1
make: *** [wxbuild] Error 2
builder for `/nix/store/2587m38s6cjjpx7mvn85x8z65brf6nps-trueCrypt-6.0a.drv' failed with exit code 2
error: build of `/nix/store/2587m38s6cjjpx7mvn85x8z65brf6nps-trueCrypt-6.0a.drv' failed
--------------------

svn path=/nixpkgs/trunk/; revision=12388